import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import MaxWidthWrapper from "@/components/MaxWidthWrapper";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="min-h-[100dvh] flex flex-col">
          <MaxWidthWrapper className="flex-1">
            <main className="w-full flex flex-col">{children}</main>
          </MaxWidthWrapper>
          <MaxWidthWrapper>
            <Footer />
          </MaxWidthWrapper>
        </div>
      </body>
    </html>
  );
}
